# Generated by Django 3.1.6 on 2021-09-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('ID_Aj', models.AutoField(primary_key=True, serialize=False)),
                ('F_Agency', models.CharField(max_length=100, unique=True)),
                ('L_Agency', models.CharField(max_length=100)),
                ('Address', models.TextField(null=True)),
                ('Tel', models.CharField(max_length=50, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='upload')),
            ],
            options={
                'verbose_name_plural': 'ข้อมูลเอเจนซี่',
            },
        ),
        migrations.CreateModel(
            name='bucket_main',
            fields=[
                ('ID_bk', models.AutoField(primary_key=True, serialize=False)),
                ('sizes', models.CharField(max_length=1, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('Note', models.TextField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'ข้อมูลคลังถังน้ำแข็งหลัก',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('ID_cd', models.AutoField(primary_key=True, serialize=False)),
                ('F_Customer', models.CharField(max_length=100, null=True, unique=True)),
                ('L_Customer', models.CharField(max_length=100, null=True)),
                ('Address', models.TextField(max_length=50, null=True)),
                ('Tel', models.CharField(max_length=50, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'ข้อมูลลูกค้า',
            },
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('ID_List', models.AutoField(primary_key=True, serialize=False)),
                ('Name_List', models.CharField(max_length=100)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'ข้อมูลรายการ',
            },
        ),
    ]
