# Generated by Django 3.1.6 on 2021-09-11 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appMain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='Agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appMain.agency'),
        ),
        migrations.AddField(
            model_name='list',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Agency_rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('Rental_period', models.DateTimeField()),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('List', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appMain.list')),
                ('bucket_main', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appMain.bucket_main')),
            ],
            options={
                'verbose_name_plural': 'ข้อมูลค่าเช่าเอเจนซี่',
            },
        ),
    ]
