# Generated by Django 3.1.6 on 2021-09-11 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appMain', '0002_auto_20210911_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency_rent',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='agency_rent',
            name='bucket_main',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appMain.bucket_main'),
        ),
    ]
