# Generated by Django 3.1.6 on 2021-09-13 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appMain', '0004_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appMain.employee'),
        ),
    ]
