# Generated by Django 3.1.6 on 2021-09-14 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appMain', '0005_list_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='bucket_damaged',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_recipient', models.CharField(blank=True, max_length=100, null=True)),
                ('Name_sender', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Note', models.TextField(blank=True, null=True)),
                ('ID_bk', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appMain.bucket_main')),
            ],
            options={
                'verbose_name_plural': 'ข้อมูลคลังถังน้ำแข็งชำรุด',
            },
        ),
    ]
