# Generated by Django 3.1.6 on 2021-09-14 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appMain', '0006_bucket_damaged'),
    ]

    operations = [
        migrations.CreateModel(
            name='bucket_lost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Note', models.TextField(blank=True, null=True)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Agency', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appMain.agency')),
                ('Customer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appMain.customer')),
                ('ID_bk', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appMain.bucket_main')),
                ('Name_List', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appMain.list')),
            ],
            options={
                'verbose_name_plural': 'ข้อมูลคลังถังน้ำแข็งสูญหาย',
            },
        ),
    ]
