# Generated by Django 3.1.6 on 2021-09-14 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appMain', '0007_bucket_lost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_rental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rental_period', models.DateTimeField()),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Customer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appMain.customer')),
                ('List', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appMain.list')),
                ('bucket_main', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Customer_idBK', to='appMain.bucket_main')),
            ],
            options={
                'verbose_name_plural': 'ข้อมูลการเช่าของลูกค้า',
            },
        ),
    ]
