# Generated by Django 3.1.6 on 2021-09-14 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appMain', '0008_customer_rental'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='Customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appMain.customer'),
        ),
    ]
