# Generated by Django 3.1.6 on 2021-09-17 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMain', '0009_list_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('ID_budget', models.AutoField(primary_key=True, serialize=False)),
                ('Name_budget', models.CharField(max_length=255)),
                ('price', models.IntegerField(blank=True, default=0, null=True)),
                ('staff', models.CharField(max_length=100)),
                ('Date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'ข้อมูลงบประมาณ',
            },
        ),
    ]
