# Generated by Django 3.1.6 on 2021-09-20 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appMain', '0011_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.IntegerField(blank=True, default=0, null=True)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Agency_rent', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appMain.agency_rent')),
                ('Name_List', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appMain.list')),
                ('bucket_main', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appMain.bucket_main')),
            ],
            options={
                'verbose_name_plural': 'ข้อมูลรายได้',
            },
        ),
    ]
