# Generated by Django 3.1.6 on 2021-09-26 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMain', '0013_auto_20210926_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='employee',
        ),
    ]
