# Generated by Django 3.1.6 on 2021-09-28 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMain', '0015_auto_20210928_1907'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'verbose_name_plural': 'ข้อมูลค่าใช้จ่าย'},
        ),
        migrations.DeleteModel(
            name='Cost',
        ),
    ]
