# Generated by Django 3.1.6 on 2021-09-09 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_queue',
            name='queue',
            field=models.CharField(max_length=255),
        ),
    ]
